### ISSUE TITLE
Inactive tags are difficult to identify

### ISSUE THREAD

**Issue by notfornothing** [dracula/google-chrome#15]
![Snipaste_2021-06-04_21-00-54](https://user-images.githubusercontent.com/43561526/120805189-12609900-c578-11eb-859f-c2088ec28219.jpg)

### Can the color of the inactive label name be visualized a bit?
To be honest, it's hard to recognize :(

**Comment by nickimola** [comment]
Hi,

Thanks for the report.
Yes we can totally modify it.

What do you suggest to make them more readable while still be able to distinguish active and inactive?

**Comment by notfornothing** [comment]
To make the title word content of the tab page more obvious, I think it can be changed to the same font color as the main tab.
However, the background color of the main label becomes very conspicuous, while the background color of other labels becomes very weak.
It is only my opinion.

**Comment by nickimola** [comment]
HI
I don't have any problem in changing it, i would like to collect some feedback to avoid having other issues opened because "they preferred the old way" :) 
any ideas on how i can ask for feedback on this?
I don't know if it's possible to do it over github to be honest...

I appreciate any suggestions

thanks

**Comment by nickimola** [comment]
Ok i figured it out based on comments from the chrome web store feedback as well.
Version 2.5 of the theme is up for approval from chrome web store and should be available shortly
